import { motion, useSpring, useTransform } from "motion/react";
import { Check, ArrowRight, Target, Sparkles, ShieldCheck, Mail, Globe, Zap, BarChart3, Activity, Layers, Network, Instagram, Facebook, Twitter } from "lucide-react";
import { useState, useEffect } from "react";
import { AuthModal } from "./AuthModal";
import { PremiumBackground3D } from "./PremiumBackground3D";
import { Murgii3DChicken } from "./Murgii3DChicken";
import { MagneticButton } from "./MagneticButton";
import { FloatingRevenueObject3D } from "./FloatingRevenueObject3D";
import { AnimatedRevenueGraph } from "./AnimatedRevenueGraph";
import { QreatoLogo } from "./QreatoLogo";

interface LandingPageProps {
  user?: any;
  onStart?: () => void;
  onLogin?: () => void;
}

export function LandingPage({ user, onStart }: LandingPageProps) {
  const [authModalOpen, setAuthModalOpen] = useState(false);
  const [authMode, setAuthMode] = useState<"login" | "signup">("signup");

  const handleLoginClick = () => {
    if (user && onStart) {
      onStart();
    } else if (onStart) {
      onStart();
    } else {
      setAuthMode("signup");
      setAuthModalOpen(true);
    }
  };

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      document.documentElement.style.setProperty('--mouse-x', `${e.clientX}px`);
      document.documentElement.style.setProperty('--mouse-y', `${e.clientY}px`);
    };
    window.addEventListener("mousemove", handleMouseMove);
    return () => window.removeEventListener("mousemove", handleMouseMove);
  }, []);

  const testimonials = [
    {
      name: "Alex Rivera",
      role: "Growth Lead at Scalar",
      content: "Murgii AI didn't just write my ads; it re-engineered my entire conversion strategy. We tracked $400k in direct revenue in 30 days.",
      image: "https://randomuser.me/api/portraits/men/32.jpg"
    },
    {
      name: "Sarah Jenkins",
      role: "Founder of Aura Agency",
      content: "The persuasion depth is unparalleled. Finally, an AI that understands human emotion instead of just templates. Murgii AI is a game changer.",
      image: "https://randomuser.me/api/portraits/women/44.jpg"
    },
    {
      name: "Marcus Chen",
      role: "SaaS Entrepreneur",
      content: "Built my entire onboarding email sequence in minutes. Conversion rate jumped 42% overnight. The ROI is literally infinite.",
      image: "https://randomuser.me/api/portraits/men/46.jpg"
    },
    {
      name: "Elena Kosta",
      role: "Direct Response Copywriter",
      content: "I was skeptical, but Murgii AI creates hooks that I couldn't even brainstorm myself. It's my secret weapon for high-ticket clients.",
      image: "https://randomuser.me/api/portraits/women/12.jpg"
    },
    {
      name: "David Miller",
      role: "E-comm Marketing Director",
      content: "Scaling from 6 to 7 figures was a nightmare until we automated our funnel assets with Murgii AI. It engineered growth effortlessly.",
      image: "https://randomuser.me/api/portraits/men/22.jpg"
    },
    {
      name: "Sofia Rossi",
      role: "Brand Strategist",
      content: "The brand voice synchronization is unbelievable. It sounds more human, more persuasive, and more 'me' than any freelancer.",
      image: "https://randomuser.me/api/portraits/women/24.jpg"
    },
    {
      name: "James T. Wilson",
      role: "Performance Marketer",
      content: "Every single iteration generated by Murgii AI is a winner. We've cut our creative testing time by 85%. Elite level intelligence.",
      image: "https://randomuser.me/api/portraits/men/86.jpg"
    }
  ];

  return (
    <div className="min-h-screen bg-[#050508] text-white overflow-x-hidden noise-bg selection:bg-[#8B5CF6]/30 relative font-sans">
      {/* Premium Subtle Grid Overlay */}
      <div 
        className="fixed inset-0 pointer-events-none z-[1] opacity-[0.04]"
        style={{
          backgroundImage: `
            linear-gradient(to right, rgba(139, 92, 246, 0.12) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(217, 70, 239, 0.12) 1px, transparent 1px)
          `,
          backgroundSize: "48px 48px"
        }}
      />

      {/* Premium 3D Ambient Background & Moving Glassmorphic UI elements */}
      <PremiumBackground3D />

      {/* Interactive Cursor Spotlight */}
      <div
        className="fixed inset-0 pointer-events-none z-10 hidden lg:block"
        style={{
          background: `radial-gradient(600px circle at var(--mouse-x, 0px) var(--mouse-y, 0px), rgba(139,92,246,0.05), transparent 80%)`
        }}
      />

      {/* Hero Section */}
      <section className="relative pt-32 pb-32 px-4 overflow-hidden">
        {/* Cinematic Atmosphere */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full bg-[radial-gradient(circle_at_center,rgba(139,92,246,0.12)_0%,transparent_70%)] pointer-events-none" />
        <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] bg-purple-900/15 rounded-full blur-[160px] pointer-events-none" />
        <div className="absolute top-[10%] right-[-10%] w-[50%] h-[50%] bg-[#D946EF]/10 rounded-full blur-[160px] pointer-events-none" />
        
        {/* Animated Grid Lines */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_50%,#000_70%,transparent_100%)]" />

        <div className="max-w-7xl mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-8 inline-flex items-center gap-3 px-5 py-2 rounded-full bg-white/5 border border-[#8B5CF6]/30 text-[10px] font-sans tracking-[0.2em] font-bold text-[#E879F9] backdrop-blur-md shadow-[0_0_25px_rgba(139,92,246,0.25)]"
          >
            <Sparkles size={14} className="animate-pulse text-[#D946EF]" />
            $500M PERSUASION INTELLIGENCE ENGINE
          </motion.div>

          {/* 3D Animated Murgii Chicken Mascot Showcase */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
            className="flex flex-col items-center justify-center mb-6"
          >
            <Murgii3DChicken size="lg" interactive={true} showPedestal={true} showHologram={true} />
          </motion.div>
          
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
            className="text-5xl sm:text-6xl md:text-[8.5rem] tracking-tighter mb-8 leading-[0.85] bg-gradient-to-b from-white via-white to-white/40 bg-clip-text text-transparent will-change-transform"
          >
            <span className="font-black bg-gradient-to-r from-white via-[#C084FC] to-[#D946EF] bg-clip-text text-transparent">MURGII</span>
            <span className="font-light text-white/80">.AI</span>
          </motion.h1>
          
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 1 }}
            className="text-lg md:text-xl text-gray-300 max-w-xl mx-auto mb-6 leading-relaxed font-medium px-4"
          >
            The $500M AI persuasion engine engineered to generate hyper-converting copy, strategic viral hooks & scalable revenue assets across funnels, launches, emails & high-stakes brands.
          </motion.p>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5, duration: 1 }}
            className="text-[10px] md:text-xs font-sans text-gray-400 uppercase tracking-[0.2em] mb-12 max-w-[280px] sm:max-w-none mx-auto"
          >
            Built for founders, creators, agencies <br /> and growth-focused brands.
          </motion.div>
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 1 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-5 px-4 bg-white/[0.02] border border-white/10 backdrop-blur-3xl p-4 md:p-8 rounded-[32px] md:rounded-[40px] w-full sm:w-fit mx-auto shadow-[0_25px_60px_rgba(0,0,0,0.8),0_0_50px_rgba(139,92,246,0.15)] relative"
          >
            {/* Inner Glow for Glass Effect */}
            <div className="absolute inset-0 rounded-[32px] md:rounded-[40px] shadow-[inset_0_0_25px_rgba(139,92,246,0.12)] pointer-events-none" />
            
            <MagneticButton
              variant="purple"
              onClick={handleLoginClick}
              className="w-full sm:w-auto px-10 py-6 text-base tracking-tight font-black rounded-2xl"
            >
              <span>Start Writing with Murgii Free</span>
              <ArrowRight size={18} />
            </MagneticButton>

            <MagneticButton 
              variant="glass"
              onClick={handleLoginClick}
              className="w-full sm:w-auto px-10 py-6 text-xs font-bold tracking-tight uppercase rounded-2xl"
            >
              Explore Intelligence
            </MagneticButton>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.5 }}
            className="mt-16 flex flex-wrap justify-center px-4"
          >
            <span className="text-[10px] md:text-sm font-sans tracking-[0.2em] md:tracking-[0.4em] font-bold text-gray-500 uppercase text-center border-t border-white/10 pt-8 w-full max-w-2xl">
              Specifically trained copywriting agent to generate $500M+ in sales
            </span>
          </motion.div>
        </div>
      </section>

      {/* Why Murgii AI Section - Testimonial Marquee */}
      <section className="py-32 relative overflow-hidden contain-paint">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-24 flex flex-col items-center">
            <motion.h2 
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-2xl sm:text-4xl md:text-6xl font-bold tracking-tight mb-8 text-white italic leading-[1.3] px-2 md:px-4 max-w-5xl"
            >
              Why Murgii AI is the last <br className="hidden sm:block" /> 
              <span className="bg-gradient-to-r from-[#8B5CF6] via-[#C084FC] to-[#D946EF] bg-clip-text text-transparent px-1 md:px-2">copywriting tool</span> 
              <span>you will ever need</span>
            </motion.h2>
            <div className="w-24 h-[1px] bg-gradient-to-r from-transparent via-[#8B5CF6] via-[#D946EF] to-transparent shadow-[0_0_15px_rgba(139,92,246,0.6)]" />
          </div>

          <div className="relative h-[600px] w-full max-w-4xl mx-auto overflow-hidden [mask-image:linear-gradient(to_bottom,transparent,black_15%,black_85%,transparent)]">
            <motion.div
              animate={{ y: ["0%", "-50%"] }}
              transition={{ 
                duration: 60, 
                repeat: Infinity, 
                ease: "linear" 
              }}
              className="flex flex-col gap-6 py-6 will-change-transform"
            >
              {[...testimonials, ...testimonials].map((t, i) => (
                <div 
                  key={i}
                  className="group relative px-6 md:px-10 py-8 rounded-[32px] bg-white/[0.02] border border-white/10 backdrop-blur-2xl transition-all duration-500 hover:bg-white/[0.04] hover:border-[#8B5CF6]/40 overflow-hidden shadow-[0_10px_30px_rgba(0,0,0,0.5)] hover:shadow-[0_15px_40px_rgba(139,92,246,0.15)]"
                >
                  {/* Premium Animated Border Glow */}
                  <motion.div 
                    animate={{ rotate: [0, 360] }}
                    transition={{ duration: 8, repeat: Infinity, ease: "linear" }}
                    className="absolute -inset-[100%] opacity-0 group-hover:opacity-20 transition-opacity pointer-events-none"
                    style={{
                      background: "conic-gradient(from 0deg, transparent, #8B5CF6, transparent, #D946EF, transparent)"
                    }}
                  />
                  
                  {/* Glowing Edge Effect */}
                  <div className="absolute inset-x-12 -bottom-px h-px bg-gradient-to-r from-transparent via-[#8B5CF6]/50 via-[#D946EF]/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                  
                  <div className="relative z-10 flex flex-col md:flex-row md:items-center gap-6">
                    <div className="relative w-16 h-16 shrink-0">
                      <img 
                        src={t.image} 
                        alt={t.name}
                        className="w-full h-full rounded-2xl object-cover border border-white/10"
                        referrerPolicy="no-referrer"
                        loading="lazy"
                        decoding="async"
                      />
                      <div className="absolute -top-1 -right-1 w-4 h-4 bg-gradient-to-tr from-[#8B5CF6] to-[#D946EF] rounded-full border-2 border-[#050508] flex items-center justify-center">
                        <Check size={8} className="text-white font-black" />
                      </div>
                    </div>
                    <div className="flex-1 space-y-3">
                      <div className="flex items-center gap-1 mb-1">
                        {[...Array(5)].map((_, idx) => (
                          <Sparkles key={idx} size={10} className="text-[#D946EF]" />
                        ))}
                      </div>
                      <p className="text-gray-300 text-base md:text-lg italic font-medium leading-relaxed">
                        "{t.content}"
                      </p>
                      <div className="flex items-center gap-3">
                        <span className="text-sm font-bold text-white">{t.name}</span>
                        <div className="w-1 h-1 rounded-full bg-gray-700" />
                        <span className="text-xs font-bold text-[#C084FC]/80 uppercase tracking-widest">{t.role}</span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>

      {/* How Murgii AI Engineers Conversion Section */}
      <section className="py-44 px-4 relative overflow-hidden">
        {/* Cinematic Background Elements */}
        <div className="absolute top-0 left-0 w-full h-[500px] bg-gradient-to-b from-purple-900/10 to-transparent pointer-events-none" />
        <div className="absolute bottom-0 right-0 w-[800px] h-[800px] bg-[#8B5CF6]/8 rounded-full blur-[180px] pointer-events-none" />
        
        <div className="max-w-7xl mx-auto">
          {/* Section Header */}
          <div className="text-center mb-32 relative">
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              className="text-[10px] font-sans text-[#E879F9] tracking-[0.5em] uppercase mb-6 flex items-center justify-center gap-2"
            >
              <Sparkles size={12} className="animate-pulse text-[#D946EF]" />
              $500M Infrastructure
            </motion.div>
            <h2 className="text-4xl md:text-8xl font-bold mb-8 tracking-tighter leading-[0.9] bg-gradient-to-b from-white to-white/40 bg-clip-text text-transparent italic">
              How Murgii AI Engineers <br className="hidden md:block" /> Conversion
            </h2>
            <div className="w-32 h-[1px] bg-gradient-to-r from-transparent via-[#8B5CF6] via-[#D946EF] to-transparent mx-auto mb-10 shadow-[0_0_20px_#8B5CF6]" />
            <p className="text-gray-400 text-base md:text-lg max-w-2xl mx-auto leading-relaxed px-6">
              Murgii AI combines behavioral psychology, conversion intelligence, and strategic AI systems to generate persuasive assets engineered for measurable business growth.
            </p>
          </div>

          <div className="space-y-44">
            {/* BLOCK 1: Psychology */}
            <FeatureBlock 
              index={1}
              title="AI Trained on Elite Conversion Psychology"
              description="Murgii AI is engineered using direct response frameworks, behavioral economics, buyer psychology & high-performing persuasion systems optimized for real-world conversion outcomes."
              trustLine="Built for modern digital markets and high-intent customer acquisition."
              points={[
                "Understands buying psychology",
                "Generates emotionally persuasive copy",
                "Adapts to customer awareness levels",
                "Creates conversion-focused messaging",
                "Engineered for revenue outcomes"
              ]}
              visual={
                <div className="relative w-full h-full flex items-center justify-center perspective-[2000px] group/vis">
                  <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(139,92,246,0.2),transparent_70%)]" />
                  
                  {/* Floating 3D Orbital System */}
                  {[...Array(3)].map((_, i) => (
                    <motion.div
                      key={i}
                      animate={{ 
                        rotateX: [45, 60, 45],
                        rotateY: [0, 360],
                        scale: [1, 1.05, 1]
                      }}
                      transition={{ 
                        duration: 20 + i * 5, 
                        repeat: Infinity, 
                        ease: "linear" 
                      }}
                      style={{ 
                        transformStyle: "preserve-3d",
                        width: 250 + i * 100,
                        height: 250 + i * 100
                      }}
                      className="absolute border border-[#8B5CF6]/15 rounded-full blur-[0.5px] will-change-transform"
                    />
                  ))}
 
                  <motion.div 
                    animate={{ rotate: 360 }}
                    transition={{ duration: 60, repeat: Infinity, ease: "linear" }}
                    className="relative w-72 h-72 border border-[#8B5CF6]/15 rounded-full flex items-center justify-center will-change-transform"
                  >
                    {[...Array(12)].map((_, i) => (
                      <div key={i} className="absolute inset-0 flex items-center justify-center" style={{ transform: `rotate(${i * 30}deg)` }}>
                         <motion.div 
                           animate={{ 
                             opacity: [0.1, 0.6, 0.1],
                             scale: [1, 1.3, 1]
                           }}
                           transition={{ duration: 3, delay: i * 0.2, repeat: Infinity }}
                           className="w-1 h-2 bg-gradient-to-t from-[#D946EF] to-transparent rounded-full translate-y-[-140px] will-change-[opacity,transform]" 
                         />
                      </div>
                    ))}
                    
                    {/* Central Core with Deep Glassmorphism */}
                    <motion.div 
                      animate={{ scale: [0.98, 1.02, 0.98] }}
                      transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                      className="w-48 h-48 bg-black/60 backdrop-blur-3xl border-2 border-[#8B5CF6]/40 rounded-full flex items-center justify-center shadow-[0_0_100px_-20px_rgba(139,92,246,0.5),inset_0_0_40px_rgba(217,70,239,0.15)] relative group/core overflow-hidden"
                      style={{ transform: "translateZ(100px)" }}
                    >
                       <div className="absolute inset-0 bg-gradient-to-tr from-[#8B5CF6]/25 via-transparent to-[#D946EF]/20 opacity-50" />
                       <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(139,92,246,0.15),transparent)]" />
                       
                       <Network size={72} className="text-[#E879F9] relative z-10 drop-shadow-[0_0_20px_rgba(217,70,239,0.7)]" />
                       
                       <motion.div 
                         animate={{ rotate: 360 }}
                         transition={{ duration: 4, repeat: Infinity, ease: "linear" }}
                         className="absolute inset-2 border-t-2 border-[#D946EF] rounded-full opacity-30"
                       />
                    </motion.div>
                  </motion.div>
 
                  {/* Floating Psychology Particles */}
                  {[...Array(8)].map((_, i) => (
                    <motion.div
                      key={`part-${i}`}
                      animate={{
                        opacity: [0.3, 0.8, 0.3],
                        scale: [1, 1.2, 1]
                      }}
                      transition={{
                        duration: 8 + i,
                        repeat: Infinity,
                        delay: i * 0.5
                      }}
                      className="absolute w-2 h-2 bg-[#D946EF] rounded-full blur-[2px]"
                      style={{
                        top: `${20 + Math.random() * 60}%`,
                        left: `${20 + Math.random() * 60}%`,
                        transform: "translateZ(150px)"
                      }}
                    />
                  ))}
                </div>
              }
            />

            {/* BLOCK 2: Systems */}
            <FeatureBlock 
              index={2}
              reversed
              title="Generate Complete Revenue Systems"
              description="Murgii AI creates interconnected conversion systems including funnels, launch assets, landing pages, email sequences, VSLs, positioning frameworks & revenue-focused campaign structures."
              points={[
                "Launch campaign generation",
                "Funnel architecture",
                "Landing page systems",
                "Email conversion flows",
                "Offer positioning intelligence",
                "Strategic CTA optimization"
              ]}
              visual={
                <div className="relative w-full h-full flex items-center justify-center p-6 sm:p-8 md:p-12 perspective-[1500px]">
                   <div className="grid grid-cols-2 gap-4 sm:gap-6 w-full max-w-[320px] xs:max-w-[380px] sm:max-w-[440px] md:max-w-[500px] lg:max-w-[460px] xl:max-w-[540px] rotate-[6deg] skew-x-[-6deg] scale-95 sm:scale-100 lg:scale-[1.05] xl:scale-110 group-hover:rotate-0 group-hover:skew-x-0 transition-all duration-700 ease-[0.16,1,0.3,1]">
                      {[
                        { icon: Layers, label: "CONVERSION ARCHITECTURE", desc: "Multi-layered logic" },
                        { icon: Zap, label: "DECISION TRIGGERS", desc: "Behavioral hooks" },
                        { icon: BarChart3, label: "REVENUE FLOWS", desc: "Monetization systems" },
                        { icon: Mail, label: "COMMUNICATION NODE", desc: "Email conversion" }
                      ].map((item, i) => (
                        <motion.div
                          key={i}
                          initial={{ opacity: 0, translateZ: -100 }}
                          whileInView={{ opacity: 1, translateZ: 0 }}
                          viewport={{ once: true }}
                          transition={{ 
                            delay: i * 0.1, 
                            duration: 1.2, 
                            ease: [0.16, 1, 0.3, 1] 
                          }}
                          style={{ transformStyle: "preserve-3d" }}
                          className="group/card relative w-full aspect-square md:aspect-auto md:h-44 xl:h-48 bg-white/[0.03] border border-white/10 rounded-[24px] sm:rounded-[32px] backdrop-blur-3xl p-4 sm:p-5 xl:p-6 flex flex-col justify-between overflow-hidden shadow-[10px_10px_35px_-10px_rgba(0,0,0,0.5)] md:shadow-[20px_20px_60px_-15px_rgba(0,0,0,0.5)] hover:border-[#8B5CF6]/50 hover:bg-white/[0.06] transition-all duration-500 hover:shadow-[0_20px_50px_rgba(139,92,246,0.2)]"
                        >
                           <div className="absolute inset-0 bg-gradient-to-br from-white/10 via-transparent to-transparent opacity-30 group-hover/card:opacity-50 transition-opacity" />
                           <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,#8B5CF6,transparent_80%)] opacity-0 group-hover/card:opacity-15 transition-opacity" />
                           
                           <div className="w-9 h-9 sm:w-11 sm:h-11 xl:w-12 xl:h-12 rounded-xl sm:rounded-2xl bg-[#8B5CF6]/15 flex items-center justify-center border border-[#8B5CF6]/30 group-hover/card:scale-110 group-hover/card:bg-[#8B5CF6]/25 transition-all duration-500">
                             <item.icon className="w-4.5 h-4.5 sm:w-5 sm:h-5 xl:w-6 xl:h-6 text-[#E879F9]" />
                           </div>
                           <div className="space-y-1 sm:space-y-2">
                              <span className="block text-[7.5px] sm:text-[9px] font-sans text-gray-400 tracking-[0.15em] sm:tracking-[0.2em] font-black uppercase">{item.label}</span>
                              <span className="block text-[11px] sm:text-[13px] text-gray-200 font-medium leading-tight">{item.desc}</span>
                           </div>

                           <motion.div 
                             animate={{ left: ["-100%", "200%"] }}
                             transition={{ duration: 3, repeat: Infinity, delay: i * 0.5 }}
                             className="absolute top-0 w-full h-[1px] bg-gradient-to-r from-transparent via-[#8B5CF6]/40 to-transparent"
                           />
                        </motion.div>
                      ))}
                   </div>

                   <div className="absolute inset-0 pointer-events-none">
                     {[...Array(6)].map((_, i) => (
                       <motion.div
                         key={i}
                         animate={{ 
                           opacity: [0.1, 0.3, 0.1]
                         }}
                         transition={{ duration: 5 + i, repeat: Infinity }}
                         className="absolute w-1 h-1 bg-white/20 rounded-full"
                         style={{
                           top: `${(i * 15) + 10}%`,
                           left: `${(i * 12) + 10}%`
                         }}
                       />
                     ))}
                   </div>
                </div>
              }
            />

            {/* BLOCK 3: Intelligence */}
            <FeatureBlock 
              index={3}
              title="Real-Time Persuasion Intelligence"
              description="Murgii AI dynamically adapts messaging tone, emotional depth, positioning strategy, and persuasive structure based on audience behavior, platform context, and conversion objectives."
              points={[
                "Emotional tone adaptation",
                "Audience-aware copywriting",
                "Premium brand positioning",
                "Creator-focused storytelling",
                "Platform-native optimization"
              ]}
              visual={
                <div className="relative w-full h-full flex flex-col items-center justify-center gap-8 md:gap-16 p-6 md:p-16 overflow-hidden perspective-[1500px]">
                   <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(139,92,246,0.15),transparent_70%)]" />
                   
                   {/* Advanced 3D Waveform */}
                   <div className="relative w-full h-32 flex items-center justify-center gap-1.5 md:gap-2 contain-layout">
                     {[...Array(16)].map((_, i) => (
                       <motion.div
                         key={i}
                         animate={{ 
                           height: [15, 60 + (i % 5) * 10, 15],
                           opacity: [0.3, 1, 0.3],
                         }}
                         transition={{ 
                           duration: 10 + (i * 0.5), 
                           repeat: Infinity, 
                           ease: "easeInOut"
                         }}
                         style={{ transform: "translateZ(50px)" }}
                         className="w-2 md:w-3 bg-gradient-to-t from-[#8B5CF6] to-[#D946EF] rounded-full shadow-[0_0_20px_rgba(139,92,246,0.4)] will-change-[height,opacity]"
                       />
                     ))}
                   </div>
 
                   {/* Premium Status Modules */}
                   <div className="grid grid-cols-2 gap-4 md:gap-6 w-full">
                      {[
                        { label: "EMOTIONAL CALIBRATION", value: "98.4%", icon: Target, status: "PEAK" },
                        { label: "PERSUASION DEPTH", value: "ELITE", icon: Sparkles, status: "ACTIVE" },
                        { label: "AUDIENCE AWARENESS", value: "ACTIVE", icon: Activity, status: "SYNCED" },
                        { label: "CONVERSION OPTIM", value: "SYNCED", icon: Zap, status: "OPTIMIZED" }
                      ].map((item, i) => (
                        <motion.div 
                          key={i}
                          whileHover={{ translateZ: 50, scale: 1.05 }}
                          className="relative p-5 rounded-3xl bg-white/[0.02] border border-white/10 flex flex-col gap-3 backdrop-blur-3xl transition-all duration-500 hover:bg-white/[0.06] hover:border-[#8B5CF6]/40 group will-change-transform shadow-[0_20px_40px_-15px_rgba(0,0,0,0.4)]"
                        >
                           <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent opacity-30 rounded-3xl" />
                           <div className="flex items-center justify-between relative z-10">
                             <div className="flex flex-col gap-1">
                               <span className="text-[8px] font-sans text-gray-400 tracking-[0.2em] font-black uppercase">{item.label}</span>
                               <div className="flex items-center gap-2">
                                 <div className="w-1 h-1 rounded-full bg-[#D946EF] animate-pulse" />
                                 <span className="text-[7px] text-white/40 font-bold tracking-widest">{item.status}</span>
                               </div>
                             </div>
                             <div className="w-8 h-8 rounded-xl bg-white/5 flex items-center justify-center border border-white/10 group-hover:bg-[#8B5CF6]/15 group-hover:border-[#8B5CF6]/40 transition-all">
                               <item.icon size={14} className="text-[#E879F9]" />
                             </div>
                           </div>
                           <span className="text-xl md:text-2xl font-sans text-white font-bold tracking-tighter relative z-10">{item.value}</span>
                        </motion.div>
                      ))}
                   </div>
                </div>
              }
            />

            {/* BLOCK 4: Growth */}
            <FeatureBlock 
              index={4}
              reversed
              title="Built for High-Stakes Growth"
              description="Designed for founders, creators, agencies, and brands that depend on strategic communication to increase trust, attention, conversions, and scalable revenue growth."
              points={[
                "Engineered for scaling brands",
                "Optimized for high-converting campaigns",
                "Strategic storytelling systems",
                "Premium communication frameworks",
                "Elite AI writing infrastructure"
              ]}
              visual={
                <div className="relative w-full h-full p-8 md:p-20 flex flex-col gap-10 md:gap-16 bg-[#08070E]/80 backdrop-blur-3xl overflow-hidden perspective-[2000px] group/growth">
                   {/* Animated Background Flow */}
                   <div className="absolute inset-0 opacity-20">
                      <div className="absolute top-0 left-0 w-full h-full bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:2rem_2rem]" />
                      <motion.div 
                        animate={{ x: ["-100%", "100%"] }}
                        transition={{ duration: 10, repeat: Infinity, ease: "linear" }}
                        className="absolute inset-0 bg-gradient-to-r from-transparent via-[#8B5CF6]/10 to-transparent skew-x-[-45deg]"
                      />
                   </div>

                   <div className="flex items-center justify-between relative z-10" style={{ transform: "translateZ(60px)" }}>
                     <div className="flex flex-col gap-1">
                        <span className="text-[10px] md:text-[12px] font-sans text-[#E879F9] tracking-[0.4em] font-black uppercase drop-shadow-sm">REVENUE ARCHITECTURE</span>
                        <span className="text-2xl md:text-4xl font-bold text-white tracking-tighter italic">Frontier Scaling Engine</span>
                     </div>
                     <motion.div 
                       animate={{ 
                         rotate: [0, 10, -10, 0],
                         scale: [1, 1.1, 1]
                       }}
                       transition={{ duration: 5, repeat: Infinity }}
                       className="w-14 h-14 md:w-20 md:h-20 rounded-2xl md:rounded-3xl bg-gradient-to-br from-[#8B5CF6] via-[#A855F7] to-[#D946EF] flex items-center justify-center border border-white/20 shadow-[0_0_50px_rgba(139,92,246,0.5)]"
                     >
                        <Activity size={36} className="text-white" />
                     </motion.div>
                   </div>
                   
                   <div className="flex-1 w-full flex items-end justify-between gap-3 md:gap-6 pb-6 relative z-10" style={{ transformStyle: "preserve-3d" }}>
                      {[50, 75, 60, 110, 85, 120, 160].map((h, i) => (
                        <motion.div
                          key={i}
                          initial={{ height: 0, translateZ: 0 }}
                          whileInView={{ height: `${(h / 160) * 100}%` }}
                          whileHover={{ translateZ: 60, scaleX: 1.1, filter: "brightness(1.5)" }}
                          transition={{ 
                            duration: 2, 
                            delay: i * 0.1, 
                            ease: [0.16, 1, 0.3, 1] 
                          }}
                          className="relative flex-1 group/bar will-change-[height,transform] cursor-pointer"
                        >
                           {/* 3D Glass Pillar Effect */}
                           <div className="absolute inset-0 bg-gradient-to-t from-[#8B5CF6] via-[#C084FC]/70 to-[#D946EF]/50 rounded-t-2xl shadow-[0_0_40px_rgba(139,92,246,0.3)] border-t border-x border-white/30" />
                           <div className="absolute inset-[1px] bg-white/10 rounded-t-2xl backdrop-blur-sm opacity-50" />
                           
                           {/* Top Glow Cap */}
                           <div className="absolute inset-x-0 top-0 h-2 bg-white rounded-full blur-[3px] opacity-70 translate-y-[-1px]" />
                           
                           {/* Internal Energy Line */}
                           <motion.div 
                             animate={{ top: ["100%", "0%"], opacity: [0, 1, 0] }}
                             transition={{ duration: 2, delay: i * 0.2, repeat: Infinity }}
                             className="absolute inset-x-2 w-px bg-white mx-auto blur-[1px]"
                           />

                           {/* Floating Tooltip */}
                           <motion.div 
                             initial={{ opacity: 0, y: 0 }}
                             whileHover={{ opacity: 1, y: -45 }}
                             className="absolute top-0 left-1/2 -translate-x-1/2 pointer-events-none bg-white py-1 px-3 rounded-lg shadow-xl"
                           >
                             <span className="text-[10px] font-black text-black tracking-tight">+{(h * 1.8).toFixed(1)}%</span>
                             <div className="absolute bottom-[-4px] left-1/2 -translate-x-1/2 w-2 h-2 bg-white rotate-45" />
                           </motion.div>
                        </motion.div>
                      ))}
                   </div>
 
                   <div className="flex justify-between text-[10px] font-sans text-gray-500 border-t border-white/10 pt-6 tracking-[0.4em] font-black uppercase relative z-10">
                      {[ "JAN", "MAR", "MAY", "JUL", "SEP", "NOV", "DEC"].map(m => <span key={m} className="hover:text-[#D946EF] transition-colors cursor-default">{m}</span>)}
                   </div>
                   
                   {/* Cinematic Surface Glow */}
                   <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[120%] h-32 bg-[radial-gradient(ellipse_at_bottom,rgba(139,92,246,0.25),transparent_70%)] pointer-events-none" />
                </div>
              }
            />
          </div>
        </div>
      </section>

      {/* $500M LIVE REVENUE & PERSUASION ENGINE SHOWCASE */}
      <section className="py-36 px-4 relative overflow-hidden">
        {/* Cinematic ambient background glow and subtle grid */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[900px] bg-[radial-gradient(circle,rgba(139,92,246,0.12)_0%,transparent_70%)] pointer-events-none blur-[120px]" />
        
        <div className="max-w-7xl mx-auto relative z-10">
          <div className="text-center mb-16 px-4">
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-[#8B5CF6]/15 border border-[#8B5CF6]/30 text-[10px] font-black text-[#E879F9] uppercase tracking-[0.25em] mb-6 backdrop-blur-md shadow-[0_0_20px_rgba(139,92,246,0.25)]"
            >
              <Activity size={12} className="animate-pulse text-[#D946EF]" />
              $500M LIVE TELEMETRY MATRIX
            </motion.div>
            <h2 className="text-4xl md:text-8xl font-bold tracking-tighter mb-6 bg-gradient-to-b from-white via-white to-white/40 bg-clip-text text-transparent italic leading-[0.95]">
              Real-Time Revenue <br /> & Persuasion Analytics
            </h2>
            <p className="text-gray-400 text-base md:text-lg max-w-2xl mx-auto leading-relaxed">
              Every copy asset generated by Murgii AI undergoes multi-vector psychological testing to maximize click-through rate, conversions, and direct-response returns.
            </p>
          </div>

          {/* Dual 3D Vault & Live Graph Showcase */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
            {/* 3D Revenue Vault Object with Orbiting Telemetry */}
            <div className="lg:col-span-5 flex flex-col items-center justify-center p-8 rounded-[32px] bg-black/60 border border-white/10 backdrop-blur-3xl shadow-[0_25px_60px_rgba(0,0,0,0.7)] relative group">
              <div className="absolute top-4 left-6 flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-[#D946EF] animate-ping" />
                <span className="text-[10px] font-mono text-gray-400 uppercase tracking-widest">3D REVENUE VAULT</span>
              </div>
              <FloatingRevenueObject3D className="w-full h-[360px]" />
              <div className="text-center mt-2">
                <span className="text-xs font-mono text-[#C084FC] font-bold tracking-widest uppercase">
                  CALIBRATED FOR HIGH-TICKET ASSETS
                </span>
              </div>
            </div>

            {/* Interactive Animated Revenue Graph */}
            <div className="lg:col-span-7">
              <AnimatedRevenueGraph />
            </div>
          </div>
        </div>
      </section>

      {/* Footer Ecosystem */}
      <footer className="relative pt-20 pb-12 overflow-hidden border-t border-white/5 bg-transparent">
        {/* Cinematic Ambient Glows */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[1px] bg-gradient-to-r from-transparent via-[#8B5CF6]/40 via-[#D946EF]/40 to-transparent" />
        <div className="absolute top-0 right-[10%] w-[400px] h-[400px] bg-purple-900/10 rounded-full blur-[120px] pointer-events-none" />
        <div className="absolute bottom-[-10%] left-[10%] w-[300px] h-[300px] bg-[#D946EF]/8 rounded-full blur-[120px] pointer-events-none" />

        <div className="max-w-7xl mx-auto px-6 relative z-10">
          <div className="flex flex-col lg:flex-row justify-between items-start gap-12 pb-16 border-b border-white/5">
            {/* BRAND & VALUE PROP */}
            <div className="max-w-md space-y-6">
              <div className="flex items-center gap-3 group cursor-pointer" onClick={onStart}>
                <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-[#8B5CF6] to-[#D946EF] flex items-center justify-center shadow-[0_0_25px_rgba(139,92,246,0.6)] group-hover:scale-110 transition-transform">
                  <QreatoLogo size={22} className="text-white" />
                </div>
                <div className="tracking-tighter text-white uppercase text-2xl italic">
                  <span className="font-extrabold bg-gradient-to-r from-white via-[#C084FC] to-[#D946EF] bg-clip-text text-transparent">MURGII</span>
                  <span className="font-light text-white/80">.AI</span>
                </div>
              </div>
              <p className="text-gray-400 text-sm leading-relaxed font-medium">
                Murgii AI is a $500M persuasion intelligence system engineered for founders, creators, agencies, and brands building scalable revenue through strategic communication.
              </p>
              <div className="flex flex-wrap gap-4 pt-2">
                {[
                  { label: "AI-Powered Infrastructure", icon: Layers },
                  { label: "Enterprise-Grade Security", icon: ShieldCheck },
                  { label: "Premium Conversion Intelligence", icon: Target }
                ].map((trust, i) => (
                  <div key={i} className="flex items-center gap-2 text-[9px] font-sans text-gray-500 uppercase tracking-widest font-bold">
                    <trust.icon size={12} className="text-[#C084FC]/70" />
                    {trust.label}
                  </div>
                ))}
              </div>
            </div>

            {/* REAL APP NAVIGATION & CONNECTED CHANNELS */}
            <div className="flex flex-wrap gap-12 sm:gap-16">
              <div>
                <h4 className="text-[10px] font-sans font-black text-[#C084FC] uppercase tracking-[0.3em] mb-6">Workspace</h4>
                <ul className="space-y-4">
                  <li>
                    <button 
                      onClick={onStart}
                      className="text-xs font-bold text-gray-400 hover:text-white transition-colors relative group flex items-center gap-2 cursor-pointer"
                    >
                      <span className="w-0 h-[1px] bg-[#8B5CF6] transition-all group-hover:w-3" />
                      Launch AI Workspace
                    </button>
                  </li>
                  <li>
                    <button 
                      onClick={() => {
                        const pricingEl = document.getElementById("pricing") || document.querySelector("section:has(.MVPPriceCard)");
                        if (pricingEl) {
                          pricingEl.scrollIntoView({ behavior: "smooth" });
                        } else {
                          handleLoginClick();
                        }
                      }}
                      className="text-xs font-bold text-gray-400 hover:text-white transition-colors relative group flex items-center gap-2 cursor-pointer"
                    >
                      <span className="w-0 h-[1px] bg-[#8B5CF6] transition-all group-hover:w-3" />
                      MVP Free Access
                    </button>
                  </li>
                  <li>
                    <button 
                      onClick={handleLoginClick}
                      className="text-xs font-bold text-gray-400 hover:text-white transition-colors relative group flex items-center gap-2 cursor-pointer"
                    >
                      <span className="w-0 h-[1px] bg-[#8B5CF6] transition-all group-hover:w-3" />
                      Sign In / Account
                    </button>
                  </li>
                </ul>
              </div>

              <div>
                <h4 className="text-[10px] font-sans font-black text-[#C084FC] uppercase tracking-[0.3em] mb-6">Connect</h4>
                <ul className="space-y-4">
                  <li>
                    <a 
                      href="https://www.instagram.com/qreato.io?igsh=MTlmNHN6ampqYWF3bQ==" 
                      target="_blank" 
                      rel="noopener noreferrer" 
                      className="flex items-center gap-3 group text-xs font-bold text-gray-400 hover:text-white transition-colors"
                    >
                      <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center group-hover:bg-[#8B5CF6]/15 group-hover:border-[#8B5CF6]/40 transition-all">
                        <Instagram size={15} className="text-gray-400 group-hover:text-[#D946EF] transition-colors" />
                      </div>
                      <span>Instagram</span>
                    </a>
                  </li>
                  <li>
                    <a 
                      href="https://x.com/s4lma9" 
                      target="_blank" 
                      rel="noopener noreferrer" 
                      className="flex items-center gap-3 group text-xs font-bold text-gray-400 hover:text-white transition-colors"
                    >
                      <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center group-hover:bg-[#8B5CF6]/15 group-hover:border-[#8B5CF6]/40 transition-all">
                        <Twitter size={15} className="text-gray-400 group-hover:text-[#D946EF] transition-colors" />
                      </div>
                      <span>X / Twitter</span>
                    </a>
                  </li>
                  <li>
                    <a 
                      href="https://whop.com/qreato/ai-leverage" 
                      target="_blank" 
                      rel="noopener noreferrer" 
                      className="flex items-center gap-3 group text-xs font-bold text-gray-400 hover:text-white transition-colors"
                    >
                      <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center group-hover:bg-[#8B5CF6]/15 group-hover:border-[#8B5CF6]/40 transition-all">
                        <Target size={15} className="text-gray-400 group-hover:text-[#D946EF] transition-colors" />
                      </div>
                      <span>Whop Upgrade Portal</span>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* LEGAL + TRUST STRIP */}
          <div className="pt-8 flex flex-col md:flex-row justify-between items-center gap-6 relative">
            <div className="flex flex-col sm:flex-row items-center gap-3 sm:gap-6 text-center sm:text-left">
              <p className="text-[11px] font-sans text-gray-500 uppercase tracking-[0.15em]">© 2026 Murgii Labs. All rights reserved.</p>
              <div className="hidden sm:block w-3 h-[1px] bg-white/10" />
              <p className="text-[11px] font-sans text-[#C084FC]/80 uppercase tracking-[0.2em] font-bold">Engineered with persuasion intelligence.</p>
            </div>
            
            <div className="flex items-center flex-wrap justify-center gap-6">
               {[
                 { label: "Secure Infrastructure", icon: ShieldCheck },
                 { label: "Enterprise Ready", icon: Target }
               ].map((trust, i) => (
                 <div key={i} className="flex items-center gap-2 text-[9px] font-sans text-gray-500 uppercase tracking-widest font-bold">
                   <trust.icon size={11} className="text-[#8B5CF6]" />
                   {trust.label}
                 </div>
               ))}
            </div>
          </div>
        </div>
      </footer>
      <AuthModal 
        isOpen={authModalOpen} 
        onClose={() => setAuthModalOpen(false)} 
        initialMode={authMode} 
        onSuccess={onStart} 
      />
    </div>
  );
}

interface FeatureBlockProps {
  index: number;
  title: string;
  description: string;
  trustLine?: string;
  points: string[];
  visual: React.ReactNode;
  reversed?: boolean;
}

function FeatureBlock({ index, title, description, trustLine, points, visual, reversed }: FeatureBlockProps) {
  const x = useSpring(0, { stiffness: 100, damping: 30 });
  const y = useSpring(0, { stiffness: 100, damping: 30 });

  const rotateX = useTransform(y, [-0.5, 0.5], [10, -10]);
  const rotateY = useTransform(x, [-0.5, 0.5], [-10, 10]);

  function handleMouseMove(event: React.MouseEvent<HTMLDivElement>) {
    const rect = event.currentTarget.getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;
    const mouseX = event.clientX - rect.left;
    const mouseY = event.clientY - rect.top;
    const xPct = (mouseX / width) - 0.5;
    const yPct = (mouseY / height) - 0.5;
    x.set(xPct);
    y.set(yPct);
  }

  function handleMouseLeave() {
    x.set(0);
    y.set(0);
  }

  return (
    <div className={`flex flex-col lg:flex-row items-center gap-16 md:gap-32 ${reversed ? 'lg:flex-row-reverse' : ''}`}>
      <motion.div 
        initial={{ opacity: 0, x: reversed ? 50 : -50 }}
        whileInView={{ opacity: 1, x: 0 }}
        viewport={{ once: true, margin: "-100px" }}
        transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
        className="flex-1 space-y-8"
      >
        <div className="inline-flex items-center gap-4">
           <motion.span 
             animate={{ opacity: [0.6, 1, 0.6] }}
             transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
             className="text-5xl md:text-8xl font-black bg-gradient-to-br from-[#8B5CF6] via-[#D946EF] to-white/20 bg-clip-text text-transparent tracking-tighter select-none will-change-opacity"
           >
             0{index}
           </motion.span>
           <div className="w-16 h-[1px] bg-gradient-to-r from-[#8B5CF6]/60 via-[#D946EF]/60 to-transparent" />
        </div>
        <h3 className="text-4xl md:text-6xl font-bold leading-tight tracking-tight text-white">{title}</h3>
        <div className="space-y-4">
          <p className="text-gray-300 text-lg md:text-xl leading-relaxed">{description}</p>
          {trustLine && (
            <p className="text-[#C084FC]/80 text-xs font-sans tracking-widest uppercase font-bold">{trustLine}</p>
          )}
        </div>
        <div className="space-y-4 pt-4">
           {points.map((p, i) => (
             <div key={i} className="flex items-center gap-4 group">
               <div className="w-1.5 h-1.5 rounded-full bg-[#D946EF] group-hover:scale-150 group-hover:shadow-[0_0_10px_#D946EF] transition-all" />
               <span className="text-sm md:text-base font-medium text-gray-300 group-hover:text-white transition-colors">{p}</span>
             </div>
           ))}
        </div>
      </motion.div>

      <motion.div 
        initial={{ opacity: 0, scale: 0.9, y: 30 }}
        whileInView={{ opacity: 1, scale: 1, y: 0 }}
        viewport={{ once: true, margin: "-100px" }}
        transition={{ duration: 1.2, ease: [0.16, 1, 0.3, 1] }}
        onMouseMove={handleMouseMove}
        onMouseLeave={handleMouseLeave}
        style={{ rotateX, rotateY, transformStyle: "preserve-3d" }}
        className="flex-1 w-full aspect-square md:aspect-auto md:h-[600px] relative group cursor-crosshair"
      >
        <div 
          className="absolute inset-0 rounded-[48px] bg-white/[0.03] border border-white/10 backdrop-blur-xl overflow-hidden group-hover:border-[#8B5CF6]/50 transition-all duration-700 shadow-[0_50px_100px_-20px_rgba(0,0,0,0.5)]"
          style={{ transform: "translateZ(50px)", transformStyle: "preserve-3d" }}
        >
           <div className="absolute inset-0 bg-gradient-to-br from-white/[0.08] via-transparent to-transparent" />
           <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(139,92,246,0.15),transparent_50%)]" />
           <div className="relative w-full h-full flex items-center justify-center" style={{ transform: "translateZ(80px)" }}>
             {visual}
           </div>
        </div>
        
        {/* Floating Accents */}
        <div className="absolute -top-10 -right-10 w-40 h-40 bg-[#8B5CF6]/15 rounded-full blur-[100px] opacity-0 group-hover:opacity-100 transition-opacity duration-1000" />
        <div className="absolute -bottom-10 -left-10 w-40 h-40 bg-[#D946EF]/15 rounded-full blur-[100px] opacity-0 group-hover:opacity-100 transition-opacity duration-1000" />
      </motion.div>
    </div>
  );
}
